on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  combine2pyhf:
    runs-on: ubuntu-latest
    container: 
      image: kskovpen/combine2pyhf:latest      
      options: --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    name: Run combine2pyhf tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run tests
        shell: bash
        run: /.dockerenv | validation/test.sh
      - name: Publish results
        uses: actions/upload-artifact@v3
        with:
          name: log.tar.gz
          path: /__w/combine2pyhf/combine2pyhf/log.tar.gz
