on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  combine2pyhf:
    runs-on: ubuntu-latest
    container: 
      image: kskovpen/combine2pyhf:latest      
      options: --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    name: Run combine2pyhf tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run tests
        shell: bash
        run: /.dockerenv | validation/test.sh
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /__w/combine2pyhf/combine2pyhf/logs
      - name: Publish results
        uses: actions-x/commit@v6
        with:
          name: actionbot
          branch: master
          files: /__w/combine2pyhf/combine2pyhf/validation/results
          repository: https://github.com/kskovpen/combine2pyhf
          token: ${{ secrets.MY_SECRET_TOKEN }}
          force: true
          message: 'automated publication of results'
