on: push

jobs:
  combine2pyhf:
    runs-on: ubuntu-latest
    container: 
      image: kskovpen/combine2pyhf:latest
      options: -v "$PWD/validation:/validation" --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    name: Run combine2pyhf tests
    steps:
      - name: Run tests
        run: /.dockerenv | /validation/test.sh
