on: push

jobs:
  combine2pyhf:
    runs-on: ubuntu-latest
    container: 
      image: kskovpen/combine2pyhf:latest
      options: --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    name: Run combine2pyhf tests
    inputs:
      repo_path:
        description: /validation
	required: true
    steps:
      - name: Run tests
        run: /.dockerenv | /validation/test.sh
